baseURL = "https://komittee-express.netlify.com/"
languageCode = "ja"
title = "Komittee Express"
theme = "hugo_theme_robust"
hasCJKLanguage = true
enableGitInfo = true

[params]
  description = "ITエンジニアと演奏家の、二足の草鞋を履こうとする17JKのブログ"

[taxonomies]
  tag = "tags"

[params.author]
  thumbnail = "images/author.jpg"
  name = "国見小道"
  description = "<p>フリーランス3年生</p>"
  twitter = "https://twitter.com/kunimi_komichi"
  github = "https://github.com/kunimi53chi"
